-- Adcionado outras permissoes
INSERT INTO tb13_permissao (tb13_descricao) VALUES
('ROLE_PESQUISAR_VOLUNTARIO'),('ROLE_PRESQUISAR_VAGAVOLUNTARIO'),('ROLE_PESQUISAR_ENTIDADE'),
('ROLE_PESQUISAR_CIDADE');
